import 'package:flutter/material.dart';
import 'way2quran_repository.dart';
import 'way2quran_models.dart';

class Way2QuranHomeScreen extends StatefulWidget{const Way2QuranHomeScreen({super.key});@override State<Way2QuranHomeScreen> createState()=>_Way2QuranHomeScreenState();}
class _Way2QuranHomeScreenState extends State<Way2QuranHomeScreen>{
 final repo=Way2QuranRepository(); String query=''; late Future<List<Way2QuranReciter>> future;
 @override void initState(){super.initState();future=repo.getReciters();}
 void refresh(){setState(()=>future=repo.getReciters(search:query));}
 @override Widget build(BuildContext context){final ar=Localizations.localeOf(context).languageCode=='ar';return Scaffold(
 appBar:AppBar(title:Text(ar?'القراءات والروايات':'Qira’at & Riwayat'),centerTitle:true),
 body:ListView(padding:const EdgeInsets.all(16),children:[
  Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
   Text(ar?'Way2Quran داخل وردي':'Way2Quran inside Wirdi',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),
   const SizedBox(height:8),Text(ar?'تجربة القراءات والروايات والقراء بنفس مصدر Way2Quran، داخل واجهة وردي.':'Way2Quran recitations, riwayat and reciters using the same API, inside Wirdi.'),
   const SizedBox(height:14),TextField(decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:ar?'ابحث عن قارئ':'Search reciter',border:const OutlineInputBorder()),onChanged:(v){query=v;},onSubmitted:(_)=>refresh()),
  ])),
  const SizedBox(height:16),Text(ar?'الروايات':'Recitations',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:8),
  Wrap(spacing:8,runSpacing:8,children:Way2QuranRepository.recitations.map((r)=>ActionChip(label:Text(r.name(ar)),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>Way2QuranRecitersScreen(recitation:r)))).toList()),
  const SizedBox(height:18),Text(ar?'القراء':'Reciters',style:const TextStyle(fontSize:19,fontWeight:FontWeight.w800)),const SizedBox(height:8),
  FutureBuilder<List<Way2QuranReciter>>(future:future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Card(child:ListTile(leading:const Icon(Icons.cloud_off),title:Text(ar?'تعذر الاتصال بمصدر Way2Quran':'Way2Quran source unavailable'),subtitle:Text('${s.error}'),trailing:IconButton(onPressed:refresh,icon:const Icon(Icons.refresh))));final list=s.data??const [];return Column(children:list.map((r)=>Card(child:ListTile(leading:r.photo.isEmpty?const CircleAvatar(child:Icon(Icons.person)):CircleAvatar(backgroundImage:NetworkImage(r.photo)),title:Text(r.name(ar),textAlign:ar?TextAlign.right:TextAlign.left),subtitle:Text(ar?'المشاهدات: ${r.totalViews}':'Views: ${r.totalViews}'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>Way2QuranReciterScreen(reciterSlug:r.slug))))).toList());})
 ]) );}
}
class Way2QuranRecitersScreen extends StatefulWidget{final Way2QuranRecitation recitation;const Way2QuranRecitersScreen({super.key,required this.recitation});@override State<Way2QuranRecitersScreen> createState()=>_Way2QuranRecitersScreenState();}
class _Way2QuranRecitersScreenState extends State<Way2QuranRecitersScreen>{late Future<List<Way2QuranReciter>> future;@override void initState(){super.initState();future=Way2QuranRepository().getReciters(recitationSlug:widget.recitation.slug);}
@override Widget build(BuildContext context){final ar=Localizations.localeOf(context).languageCode=='ar';return Scaffold(appBar:AppBar(title:Text(widget.recitation.name(ar)),centerTitle:true),body:FutureBuilder<List<Way2QuranReciter>>(future:future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text(ar?'تعذر تحميل القراء':'Could not load reciters'));final list=s.data??const [];return GridView.builder(padding:const EdgeInsets.all(16),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.sizeOf(context).width>=900?4:MediaQuery.sizeOf(context).width>=600?3:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:.82),itemCount:list.length,itemBuilder:(c,i){final r=list[i];return Card(child:InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>Way2QuranReciterScreen(reciterSlug:r.slug))),child:Column(children:[Expanded(child:r.photo.isEmpty?const Icon(Icons.person,size:56):Image.network(r.photo,fit:BoxFit.cover,width:double.infinity,errorBuilder:(_,__,___)=>const Icon(Icons.person,size:56))),Padding(padding:const EdgeInsets.all(8),child:Text(r.name(ar),maxLines:2,overflow:TextOverflow.ellipsis,textAlign:TextAlign.center))])));});}));}}
class Way2QuranReciterScreen extends StatefulWidget{final String reciterSlug;const Way2QuranReciterScreen({super.key,required this.reciterSlug});@override State<Way2QuranReciterScreen> createState()=>_Way2QuranReciterScreenState();}
class _Way2QuranReciterScreenState extends State<Way2QuranReciterScreen>{late Future<Way2QuranReciter> future;int selected=0;@override void initState(){super.initState();future=Way2QuranRepository().getReciter(widget.reciterSlug);}
@override Widget build(BuildContext context){final ar=Localizations.localeOf(context).languageCode=='ar';return Scaffold(appBar:AppBar(title:Text(ar?'القارئ':'Reciter')),body:FutureBuilder<Way2QuranReciter>(future:future,builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text(ar?'تعذر تحميل بيانات القارئ':'Could not load reciter'));final r=s.data!,recs=r.recitations;if(recs.isEmpty)return Center(child:Text(ar?'لا توجد روايات':'No recitations'));selected=selected.clamp(0,recs.length-1);final rec=recs[selected];return ListView(padding:const EdgeInsets.all(16),children:[Card(child:ListTile(leading:r.photo.isEmpty?const CircleAvatar(child:Icon(Icons.person)):CircleAvatar(backgroundImage:NetworkImage(r.photo)),title:Text(r.name(ar)),subtitle:Text(ar?'المشاهدات: ${r.totalViews}':'Views: ${r.totalViews}'))),const SizedBox(height:12),DropdownButtonFormField<int>(value:selected,decoration:InputDecoration(labelText:ar?'الرواية':'Riwayah',border:const OutlineInputBorder()),items:List.generate(recs.length,(i)=>DropdownMenuItem(value:i,child:Text(recs[i].name(ar)))),onChanged:(v){if(v!=null)setState(()=>selected=v);}),const SizedBox(height:12),for(final a in rec.audioFiles)Card(child:ListTile(leading:const Icon(Icons.play_circle_outline),title:Text(a.surahName.isEmpty?'سورة ${a.surahNumber}':a.surahName),subtitle:Text(a.url.isEmpty?a.downloadUrl:a.url))),if(rec.downloadUrl.isNotEmpty)FilledButton.icon(onPressed:()=>Way2QuranRepository().incrementDownload(rec.slug),icon:const Icon(Icons.download),label:Text(ar?'تحميل المصحف':'Download Mushaf'))]);}));}}
